env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  -
    ldflags: -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - i386
    goamd64:
      - v3
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  build_flag_templates:
    - "--build-arg COMMIT_SHA={{ .Commit }}"
    - "--build-arg REPO_URL={{ .RepoURL }}"
