  name: 'Golang Jenkins Client'
  description: 'Trigger a Jenkins job, wait for its result, have jenkins output in githubactions.'
  branding:
      icon: "check"
      color: orange
  inputs:
      base_url:
          description: 'Jenkins server URL'
          required: true
      job_name:
        description: 'Jenkins job name'
        required: true
      user:
          description: 'Jenkins user'
          required: true
      password:
          description: 'Jenkins user password'
          required: true
      job_parameters:
        description: 'Jenkins job parameters'
        required: false
      wait_timeout:
        description: 'Wait timeout'
        required: false
        default: 1h
      polling_interval:
        description: 'Interval to poll for result'
        required: false
        default: 1s

  runs:
      image: "docker://scylladb/github-actions:jenkins-client-v0.1.0"
      using: "docker"
      args:
          - --job-name=${{ inputs.job_name }}
          - --job-parameters=${{ inputs.job_parameters }}
          - --wait-timeout=${{ inputs.wait_timeout }}
          - --wait-pooling-interval=${{ inputs.polling_interval }}
          - --base-url=${{ inputs.base_url }}
          - --user=${{ inputs.user }}
          - --password=${{ inputs.password }}
